### ISSUE TITLE
Grafana 7

### ISSUE THREAD

**Issue by meyerder** [GoshPosh/grafana-meta-queries#104]
I cant seem to get this to work on Grafana 7.0 even when it is a signed plugin

**Comment by mazamsezer** [comment]
Same here. I installed Grafana Enterpeise 7. I had one dashboard with three panels having MetaQueries, working on 6:latest (I am using Docker) which stopped working on Enterprise 7.

It says cannot read the length of null or something similiar. As I do not have access to my PC at the moment, I cannot give you the exact error.

Is there anything I can do make it work?

**Comment by meyerder** [comment]
Yep I was/am running enterprise as well at this time but it appears on the
community edition on 7 as well

**Comment by gonfunko** [comment]
I'm seeing what I think is the same issue after updating Grafana; my config was previously working. Error message and queries are attached.
<img width="1185" alt="Screen Shot 2020-07-16 at 9 25 50 PM" src="https://user-images.githubusercontent.com/667459/87748658-5b1a3280-c7ab-11ea-9a03-cbd2ea605c58.png">
<img width="831" alt="Screen Shot 2020-07-16 at 9 27 26 PM" src="https://user-images.githubusercontent.com/667459/87748660-5bb2c900-c7ab-11ea-8a27-a939153baf4e.png">

**Comment by TheRealKerni** [comment]
@gonfunko happens here on 7.1 as well. Grafana 7.0.x works fine with the current version. So there must be changes in 7.1 regarding how plugins works.

**Comment by Gauravshah** [comment]
verified it works with 7.0.3, but doesn't work with 7.1.x. Release notes don't have any breaking changes. Will look into and get back in couple of days

**Comment by meyerder** [comment]
Must be I am doing something wrong...   7.02

**Comment by meyerder** [comment]
I must be doing something wrong.. I set it to mixed (7.02) and tell it to leverage Query A... Cannot set property 'hide' of undefined

**Comment by meyerder** [comment]
Figured out how to reopen...

**Comment by cjs226** [comment]
Same, not working on 7.0.5.

**Comment by arigit** [comment]
Same issue on 7.1.1 enterprise - missing this great plugin

**Comment by earth08** [comment]
I have same issue,
When selecting metaqueries as datasource, no data is displayed.
Well hope everything gets fixed asap.
I am using grafana 7.1.1 as docker provided by frenk as adding for home assistant.

**Comment by Gauravshah** [comment]
This seems to be fixed in 7.1.3
[
<img width="1266" alt="Screenshot 2020-08-12 at 5 15 49 AM" src="https://user-images.githubusercontent.com/620559/90013890-ff807f00-dc5a-11ea-9ad8-035097478c99.png">
](url)

**Comment by arigit** [comment]
@Gauravshah I confirm the same, I can now add metaqueries to my panels.

However, at least in the moving average case, the behavior with Moving Averages seems weird, it seems to be just scaling down the main graph by a factor equal to the amount of periods I choose for the average.
E.g. if I select Periods = 2, the "moving average" graph is the same as the main graph by divided by two.
WIth Period = 4:

![image](https://user-images.githubusercontent.com/652673/90048589-bef82400-dca1-11ea-8550-145b06184ffc.png)

![image](https://user-images.githubusercontent.com/652673/90048993-3af26c00-dca2-11ea-8600-ffe2837f8d5f.png)

![image](https://user-images.githubusercontent.com/652673/90048865-10081800-dca2-11ea-95ab-f39b94bc5c0e.png)

Could this be a bug?

**Comment by Gauravshah** [comment]
@arigit can you open a different ticket ?
was this working before ? 
can you post a screenshot with data in table form ? that will better help us compare numbers
also Moving Average computes over last 4 days ( for period =4) and not last 4 data points

**Comment by arigit** [comment]
Thanks @Gauravshah - I will open a ticket later today and attach the data. This wasn't working before, I'm new to this plugin and it seems to fit my needs perfectly if I can get it to work. My challenge is that I'm trying to apply it to an IP bandwidth graph that is sampled once every 10 seconds, so a 1-day moving average won't cut it. In the IP/networks world 5-minute moving averages are most common and this is what I was trying to obtain with the addon. I tried using fractional numbers in the Period fields but that didn't work either. We can continue the discussing in the new ticket.

**Comment by Gauravshah** [comment]
we added support for timeshiftUnits I think we need to add same for Moving Average that should fix your issue.
https://github.com/GoshPosh/grafana-meta-queries/pull/62/files

**Comment by arigit** [comment]
Opened #107; I believe #104 has been solved

**Comment by TheRealKerni** [comment]
@Gauravshah it seems to work with the Grafana sample data, but existing panels don't work and creating a new panel with other data sources don't seem to work. Does this happen for you as well?

**Comment by IstvanPeter** [comment]
We have some dashboards where we have to compare the data with an earlier state and it worked till version 7.0.x.

Reproduce steps:
Create a chart with MetaQuery and select datasource for the Query "A" a Cloudwatch datasource.
Select one of the native metrics
Add a Query with datasource "MetaQuery" and set the metric name of the Query "A" 

You get "Cannot read property 'forEach' of undefined" error
![image](https://user-images.githubusercontent.com/37807551/91975406-a8347280-ed1f-11ea-9130-89f2ff903c4e.png)

**Comment by zhukaiqiang** [comment]
7.1.5 Meta-Queries still cannot be used

**Comment by earth08** [comment]
Same here not working with 7.1.5

**Comment by Chris-Tophski** [comment]
Just updated to Grafana 7.1.5 and updated all plugins. Earlier, MetaQueries caused browser crashes quite often in my case, so I stopped using it, but now I wanted to give it another try after a while. Now, my panels with MetaQueries involved completely stopped working with several different error messages, but without crashes, so far.

Currently, I only see "resultByQuery.data is undefined", but I also saw some similar to them of the other folks here. In my case this is a Graph Panel with a set of 10 InfluxQL queries, where 9 of them are aggregated by a MetaQueries Arithmetic expression. The other query that is not involved in the aggregation does return data as far as I can see in the Query Inspector, but it doesn't end up in the Graph Panel. Even when I disable the aggregation query, the other InfluxQL query is not drawn and I still get the error. I also disabled the 9 source queries before, to only show the result in the panel, which was a pretty neat property/feature of the plugin and I hope this will be kept this way.

**Comment by fe111x** [comment]
Hi,

same Problem for me with Grafana 7.1.5
Would urgently need meta-queries again.

**Comment by nadanasser** [comment]
same here on Grafana 7.1.5, arithmetic option would sort lot of work with me

**Comment by Willshield** [comment]
Hi,
I can't use CloudWatch datasource with meta-queries in Grafana 7.1.5 also.

**Comment by fadjar340** [comment]
So do I....

**Comment by arteck** [comment]
sry.. but with influxDB works not..
![grafik](https://user-images.githubusercontent.com/6681528/97107640-e10e1980-16c8-11eb-8697-60d65fc96c08.png)

**Comment by WafflesMcDuff** [comment]
Still having this problem in Grafana 7.1.5 with InfluxDB data source

**Comment by WafflesMcDuff** [comment]
Do we have an ETA on this? We're still waiting to get this functionality back.

**Comment by unbalanced** [comment]
Such a shame, many cloudwatch dashboards stoped working. Would love to understand if this is going to get fixed or should i find another solution to run my timeshift graphs on cloudwatch metrics..

**Comment by WafflesMcDuff** [comment]
Any news on 7.1.5 compatibility?
Anyone found an alternate plugin to use in the meanwhile? This is killing me on objectives set by my leaders.

**Comment by WafflesMcDuff** [comment]
Just noticed that #118  is supposed to fix compatibility with Grafana 7.x.x
I'll report back once we've tested.

**Comment by ssakuh** [comment]
Hello, 

Still broken on 7.1.7. 

![image](https://user-images.githubusercontent.com/33666705/105750413-66fe6280-5f4d-11eb-9aae-1637d75d1a52.png)

Please let us know if there is an update.

**Comment by Gauravshah** [comment]
@ssakuh have you tried latest version from git ?
Latest version is not released on grafana due to signing issues.

**Comment by WafflesMcDuff** [comment]
> @ssakuh have you tried latest version from git ?
> Latest version is not released on grafana due to signing issues.

Do we know when Grafana will certify this release?

**Comment by Gauravshah** [comment]
@WafflesMcDuff can you verify the fix so that we can close the issue.

please follow thread here for 0.0.4 release https://github.com/grafana/grafana-plugin-repository/pull/827

**Comment by WafflesMcDuff** [comment]
@Gauravshah unfortunately, my metrics team will not install it until Grafana has certified it. I'll see if I can get them to install it in a test environment.

**Comment by eloykramar** [comment]
Hello, I downloaded and installed the latest version from git (https://github.com/GoshPosh/grafana-meta-queries/archive/0.0.4.tar.gz) but still not work in grafana 7.0.6.

This is my initial metric (mysql datasource)
<img width="1435" alt="grafana-meta-query-1" src="https://user-images.githubusercontent.com/1668933/106199416-352b0d00-6194-11eb-815f-f3442db34a01.png">

When try add timeshift -> error:
<img width="1438" alt="grafana-meta-query-2" src="https://user-images.githubusercontent.com/1668933/106199556-60156100-6194-11eb-8571-a1b760132317.png">

When try add arithmetic -> no error, but nothing can be seen ->
<img width="1439" alt="grafana-meta-query-3" src="https://user-images.githubusercontent.com/1668933/106199608-7b806c00-6194-11eb-8926-7ae3ebb1b1fe.png">
<img width="1437" alt="grafana-meta-query-4" src="https://user-images.githubusercontent.com/1668933/106199622-7f13f300-6194-11eb-9569-60d1f5614b26.png">

Do you see something wrong? Thanks in advance.

**Comment by Gauravshah** [comment]
Your panel source is mixed. It should be meta queries.

**Comment by eloykramar** [comment]
Sorry for my bad, with that it works perfect! Thanks.

**Comment by zebardy** [comment]
Hi, is there any update on when the fix for this will be signed? 

Many thanks

**Comment by WafflesMcDuff** [comment]
Yes. Our grafana team says they won't implement this until the release is signed by Grafana. @Gauravshah  - where do you stand on getting the release signed?

**Comment by WafflesMcDuff** [comment]
> Yes. Our grafana team says they won't implement this until the release is signed by Grafana. @Gauravshah - where do you stand on getting the release signed?

@ShilpaSivanesan

**Comment by Gauravshah** [comment]
closing this issue as grafana 7 compatibility is fixed.
opening a different issue https://github.com/GoshPosh/grafana-meta-queries/issues/120

**Comment by matanbaruch** [comment]
![image](https://user-images.githubusercontent.com/36934912/110240514-fcc9dc00-7f54-11eb-83b2-eab9d5695a20.png)

Still does not work as expected

Grafana v7.3.4
