### ISSUE TITLE
Failed to find exported plugin component for query-ctrl-mixed

### ISSUE THREAD

**Issue by smirn0v** [GoshPosh/grafana-meta-queries#2]
Grafana 4.6.1
Getting this error with no graphs displayed
https://cloud.mail.ru/public/9cNf/u2Q9pfGXn

**Comment by Gauravshah** [comment]
can you add in steps ? I am unable to reproduce this issue on my local with grafana 4.6.1
also screenshot of dashboard config that you are building ?

**Comment by Gauravshah** [comment]
added into the dist folder in commit https://github.com/GoshPosh/grafana-meta-queries/blob/f97f945c20e968d1ed38a5d60437576a0762f53e/dist/datasource.ts

**Comment by Gauravshah** [comment]
fixed in https://github.com/GoshPosh/grafana-meta-queries/commit/f97f945c20e968d1ed38a5d60437576a0762f53e

**Comment by kccheung** [comment]
I still have the same error on grafana 4.6.3 after pulling the master code.
